version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    image: stockallj/python-test-web-frontend:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
